trigger:
- main
schedules:
- cron: '0 12 * * 0'
  displayName: Weekly Sunday build
  branches:
    include:
    - main
  always: true
  
pool:
  vmImage: 'windows-latest'

steps:
- task: CredScan@3
- task: Semmle@1
  env: 
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
  inputs:
    sourceCodeDirectory: '$(Build.SourcesDirectory)'
    language: 'python'
    querySuite: 'Recommended'
    timeout: '1800'
    ram: '16384'
    addProjectDirToScanningExclusionList: true
- task: ComponentGovernanceComponentDetection@0
  inputs:
    scanType: 'Register'
    verbosity: 'Verbose'
    alertWarningLevel: 'High'